// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jesdyxzhildssafefeht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implc2R5eHpoaWxkc3NhZmVmZWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Mjc3NDMsImV4cCI6MjA2NjEwMzc0M30.DKROMDG_ojvI7nIyZlj-faPXN2JL0gK-yodx17vWLNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);